# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 對話·機器 | Talk2.it
subtitle: A good talk to the MACHINE in front of you.
description: 和眼前的世界好好谈谈

author: Bingo
language: en
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://talk2.it
root: /
#permalink: :title.html
permalink: post/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: /categories

book_dir: /book
calendar_dir: /calendar

code_dir: downloads/code
i18n_dir: :lang
skip_render: moto/**

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 0
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#theme: next
#theme: diaspora
#theme: archer
#theme: inside
theme: inside
#theme: newside
#theme: landscape

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: git
  repo: https://github.com/omnibingo/omnibingo.github.io.git
  branch: master


- type: cos
  secretId: AKIDVpwscA0pqdDfu0rZ2ILBnJcibMuFjH1Y
  secretKey: UlpgJjz2sUt54qTxEH7kDTWnvra7QYS9
  bucket: talk2it-1253730645
  region: na-ashburn  

- type: cos
  secretId: AKIDVpwscA0pqdDfu0rZ2ILBnJcibMuFjH1Y
  secretKey: UlpgJjz2sUt54qTxEH7kDTWnvra7QYS9
  bucket: cntalk2it-1253730645
  region: ap-shanghai


#- type: git
#  repo: https://git.coding.net/omnibingo/talk2.it.git
#  branch: master

#- type: git
#  repo: https://git.coding.net/omnibingo/omnibingo.git
#  branch: master
# Avatar by Bingo
#avatar: https://ws2.sinaimg.cn/large/006tNc79gy1fi1qihrooxj30nh0nhwf4.jpg

#baidu analytics
baidu_analytics: 565449b3656cf1ea86dc69ed003f4dfc

social:
  Twitter: https://twitter.com/omnibingo
  Weibo: http://weibo.com/omnibingo
  zhihu: http://www.zhihu.com/people/omnibingo

jiathis: true


#for archer theme

markdown_it_plus:
  highlight: true
  html: true
  xhtmlOut: true
  breaks: true
  langPrefix:
  linkify: true
  typographer:
  quotes: “”‘’
  pre_class: highlight

